export const foodImages = [
  {
    id: 1,
    name: 'Ewa Aganyin and Bread',
    link: '../../images/ewaAganyinAndBread.jpg',
    price: 2000,
    category: 'Meals',
  },
  {
    id: 2,
    name: 'Jollof Rice',
    link: '../../images/jollofRice.jpg',
    price: 3500,
    category: 'Meals',
  },
  {
    id: 3,
    name: 'Amala and Abula',
    link: '../../images/amalaAndAbula.jpg',
    price: 1800,
    category: 'Swallow',
  },
  {
    id: 4,
    name: 'Dodo Rice and Meat',
    link: '../../images/dodoRiceAndMeat.jpg',
    price: 4000,
    category: 'Meals',
  },
  {
    id: 5,
    name: 'Masa',
    link: '../../images/masa.jpg',
    price: 1500,
    category: 'Meals',
  },
  {
    id: 6,
    name: 'Ofada Rice',
    link: '../../images/ofadaRice.jpg',
    price: 3000,
    category: 'Meals',
  },
  {
    id: 7,
    name: 'Amala and Meat',
    link: '../../images/amalaAndMeat.jpg',
    price: 2500,
    category: 'Swallow',
  },
  {
    id: 8,
    name: 'Almond Butter Sauce',
    link: '../../images/almondButterSauce.jpg',
    price: 5000,
    category: 'Meals',
  },
  {
    id: 9,
    name: 'Continental Recipe',
    link: '../../images/continentalRecipe.jpg',
    price: 10000,
    category: 'Meals',
  },
  {
    id: 10,
    name: 'Dodo Rice and Meat',
    link: '../../images/dodoRiceAndMeat.jpg',
    price: 6500,
    category: 'Meals',
  },
  {
    id: 11,
    name: 'Fufu and Egusi Soup',
    link: '../../images/fufu.jpg',
    price: 1990,
    category: 'Swallow',
  },
  {
    id: 12,
    name: 'Grilled Chicken',
    link: '../../images/roastedChicken.jpg',
    price: 15000,
    category: 'Meals',
  },
  {
    id: 13,
    name: 'Moin Moin with 7 lives',
    link: '../../images/moinMoinElemiMeje.jpg',
    price: 12000,
  },
  {
    id: 14,
    name: 'Naija Veggies',
    link: '../../images/naijaMeal.jpg',
    price: 11000,
    category: 'Meals',
  },
  {
    id: 15,
    name: 'Nkwobi With Cow Leg',
    link: '../../images/nkwobiSpicyCowLeg.jpg',
    price: 25000,
    category: 'Soup',
  },
  {
    id: 16,
    name: 'Ofada Rice with Egg',
    link: '../../images/ofadaRiceWithEgg.jpg',
    price: 2000,
    category: 'Meals',
  },
  {
    id: 17,
    name: 'Ogbono Soup',
    link: '../../images/ogbonoSoup.jpg',
    price: 2000,
    category: 'Soup',
  },
  {
    id: 18,
    name: 'Pap and Bean Cake',
    link: '../../images/papAndBeanCake.jpg',
    price: 2300,
    category: 'Meals',
  },
  {
    id: 19,
    name: 'Plantain and Groundnut',
    link: '../../images/plantainAndGroundnut.jpg',
    price: 2100,
    category: 'Meals',
  },
  {
    id: 20,
    name: 'Spicy Naija Veggies',
    link: '../../images/spicy.jpg',
    price: 5500,
    category: 'Meals',
  },
  {
    id: 21,
    name: 'Yamarita',
    link: '../../images/yamarita.jpg',
    price: 10500,
    category: 'Meals',
  },
  {
    id: 22,
    name: 'Ofada Elewe',
    link: '../../images/ofadaElewe.jpg',
    price: 10500,
    category: 'Meals',
  },
  {
    id: 23,
    name: 'Rice and Beans',
    link: '../../images/riceAndBeans.jpg',
    price: 10500,
    category: 'Meals',
  },
  {
    id: 24,
    name: 'Yamarita',
    link: '../../images/yamarita.jpg',
    price: 10500,
  },
];

export const foodByCategory = [
  {
    meals: [
      {
        id: 1,
        name: 'Ewa Aganyin and Bread',
        link: '../../images/ewaAganyinAndBread.jpg',
        price: 2000,
        category: 'Meals',
      },
      {
        id: 2,
        name: 'Jollof Rice',
        link: '../../images/jollofRice.jpg',
        price: 3500,
        category: 'Meals',
      },
      {
        id: 4,
        name: 'Dodo Rice and Meat',
        link: '../../images/dodoRiceAndMeat.jpg',
        price: 4000,
        category: 'Meals',
      },
      {
        id: 5,
        name: 'Masa',
        link: '../../images/masa.jpg',
        price: 1500,
        category: 'Meals',
      },
      {
        id: 6,
        name: 'Ofada Rice',
        link: '../../images/ofadaRice.jpg',
        price: 3000,
        category: 'Meals',
      },
      {
        id: 8,
        name: 'Almond Butter Sauce',
        link: '../../images/almondButterSauce.jpg',
        price: 5000,
        category: 'Meals',
      },
      {
        id: 9,
        name: 'Continental Recipe',
        link: '../../images/continentalRecipe.jpg',
        price: 10000,
        category: 'Meals',
      },
      {
        id: 10,
        name: 'Dodo Rice and Meat',
        link: '../../images/dodoRiceAndMeat.jpg',
        price: 6500,
        category: 'Meals',
      },
      {
        id: 12,
        name: 'Grilled Chicken',
        link: '../../images/roastedChicken.jpg',
        price: 15000,
        category: 'Meals',
      },
      {
        id: 13,
        name: 'Moin Moin with 7 lives',
        link: '../../images/moinMoinElemiMeje.jpg',
        price: 12000,
      },
      {
        id: 14,
        name: 'Naija Veggies',
        link: '../../images/naijaMeal.jpg',
        price: 11000,
        category: 'Meals',
      },
      {
        id: 16,
        name: 'Ofada Rice with Egg',
        link: '../../images/ofadaRiceWithEgg.jpg',
        price: 2000,
        category: 'Meals',
      },
      {
        id: 18,
        name: 'Pap and Bean Cake',
        link: '../../images/papAndBeanCake.jpg',
        price: 2300,
        category: 'Meals',
      },
      {
        id: 19,
        name: 'Plantain and Groundnut',
        link: '../../images/plantainAndGroundnut.jpg',
        price: 2100,
        category: 'Meals',
      },
      {
        id: 20,
        name: 'Spicy Naija Veggies',
        link: '../../images/spicy.jpg',
        price: 5500,
        category: 'Meals',
      },
      {
        id: 21,
        name: 'Yamarita',
        link: '../../images/yamarita.jpg',
        price: 10500,
        category: 'Meals',
      },
      {
        id: 22,
        name: 'Ofada Elewe',
        link: '../../images/ofadaElewe.jpg',
        price: 10500,
        category: 'Meals',
      },
      {
        id: 23,
        name: 'Rice and Beans',
        link: '../../images/riceAndBeans.jpg',
        price: 10500,
        category: 'Meals',
      },
      {
        id: 24,
        name: 'Yamarita',
        link: '../../images/yamarita.jpg',
        price: 10500,
      },
    ],
    soup: [
      {
        id: 1,
        name: 'Ogbono Soup',
        link: '../../images/ogbonoSoup.jpg',
        price: 2000,
        category: 'Soup',
      },
      {
        id: 2,
        name: 'Nkwobi With Cow Leg',
        link: '../../images/nkwobiSpicyCowLeg.jpg',
        price: 25000,
        category: 'Soup',
      },
      {
        id: 3,
        name: 'Okro Soup',
        link: '../../images/okro.jpg',
        price: 25000,
        category: 'Soup',
      },
      {
        id: 4,
        name: 'Edikaikong',
        link: '../../images/edikaikong.jpg',
        price: 25000,
        category: 'Soup',
      },
      {
        id: 5,
        name: 'Egusi',
        link: '../../images/egusi.jpg',
        price: 25000,
        category: 'Soup',
      },
      {
        id: 6,
        name: 'efo riro',
        link: '../../images/efoRiro.jpg',
        price: 25000,
        category: 'Soup',
      },
      {
        id: 7,
        name: 'Ofada Sauce',
        link: '../../images/ofadaSauce.jpg',
        price: 25000,
        category: 'Soup',
      },
    ],
    swallow: [
      {
        id: 1,
        name: 'Amala and Abula',
        link: '../../images/amalaAndAbula.jpg',
        price: 1800,
        category: 'Swallow',
      },
      {
        id: 2,
        name: 'Amala and Meat',
        link: '../../images/amalaAndMeat.jpg',
        price: 2500,
        category: 'Swallow',
      },
      {
        id: 3,
        name: 'Fufu and Egusi Soup',
        link: '../../images/fufu.jpg',
        price: 1990,
        category: 'Swallow',
      },
      {
        id: 4,
        name: 'Eba',
        link: '../../images/eba.jpg',
        price: 1990,
        category: 'Swallow',
      },
      {
        id: 5,
        name: 'Semovita',
        link: '../../images/semovita.jpg',
        price: 1990,
        category: 'Swallow',
      },
      {
        id: 6,
        name: 'pounded yam',
        link: '../../images/poundedYam.jpg',
        price: 1990,
        category: 'Swallow',
      },
    ],
    pasteries: [
      {
        id: 1,
        name: 'cookies',
        price: 200,
        link: '../../images/cookies.jpg',
      },
      {
        id: 2,
        name: 'Jam Doughnut',
        price: 1200,
        link: '../../images/jamDoughnut.jpg',
      },
      {
        id: 3,
        name: 'pop corn',
        price: 500,
        link: '../../images/popCorn.jpg',
      },
      {
        id: 4,
        name: 'sausage roll',
        price: 600,
        link: '../../images/sausageRoll.jpg',
      },
      {
        id: 5,
        name: 'scotch egg',
        price: 600,
        link: '../../images/scotchEgg.png',
      },
      {
        id: 6,
        name: 'Bread',
        price: 1000,
        link: '../../images/bread.jpg',
      },
      {
        id: 7,
        name: 'meat pie',
        price: 1200,
        link: '../../images/meatPie.png',
      },
      {
        id: 8,
        name: 'chicken pie',
        price: 2000,
        link: '../../images/chickenPie.jpg',
      },
      {
        id: 9,
        name: 'mini loaf cake',
        price: 2500,
        link: '../../images/miniLoafCake.jpg',
      },
      {
        id: 10,
        name: 'white bread',
        price: 3000,
        link: '../../images/whiteBread.jpg',
      },
      {
        id: 11,
        name: 'wheat bread',
        price: 4000,
        link: '../../images/wheatBread.jpg',
      },
      {
        id: 12,
        name: 'celebration cake',
        price: 20000,
        link: '../../images/celebrationCake.jpg',
      },
    ],
    drinks: [
      {
        id: 1,
        name: 'Water 75cl',
        price: 500,
        link: '../../images/water.jpg',
      },
      {
        id: 2,
        name: 'Coke Pet',
        price: 1000,
        link: '../../images/cokePet.jpg',
      },
      {
        id: 3,
        name: 'Coke Can',
        price: 1000,
        link: '../../images/cokeCan.jpg',
      },
      {
        id: 4,
        name: 'Chapman',
        price: 1000,
        link: '../../images/chapman.jpg',
      },
      {
        id: 5,
        name: 'Fanta',
        price: 1000,
        link: '../../images/fanta.jpg',
      },
      {
        id: 6,
        name: 'Sprite',
        price: 1000,
        link: '../../images/sprite.jpg',
      },
      {
        id: 7,
        name: 'Gulder',
        price: 2500,
        link: '../../images/gulder.jpg',
      },
      {
        id: 8,
        name: 'Goldberg',
        price: 2500,
        link: '../../images/goldberg.jpg',
      },
      {
        id: 9,
        name: 'Red Wine',
        price: 4000,
        link: '../../images/redWine.jpg',
      },
      {
        id: 10,
        name: 'Hennessy',
        price: 23000,
        link: '../../images/hennessy.jpg',
      },
      {
        id: 11,
        name: 'Origin',
        price: 3000,
        link: '../../images/origin.jpg',
      },
      {
        id: 12,
        name: 'Spirit',
        price: 5000,
        link: '../../images/spirit.jpg',
      },
      {
        id: 13,
        name: 'five alive',
        price: 5000,
        link: '../../images/fiveAlive.jpg',
      },
      {
        id: 14,
        name: 'chivita',
        price: 5000,
        link: '../../images/chivitaActive.jpg',
      },
      {
        id: 15,
        name: 'hollandia yoghurt 1L',
        price: 5000,
        link: '../../images/hollandia1.jpg',
      },
      {
        id: 16,
        name: 'hollandia yoghurt 5L',
        price: 5000,
        link: '../../images/hollandia5.jpg',
      },
    ],
  },
];
